image: danger89/cmake:5.1

stages:
  - test
  - build
  - release

static_code_analysis:
  stage: test
  script:
    - cppcheck --version
    - ./scripts/cpp_check.sh

code_style_guidelines:
  stage: test
  script:
    - clang-format --version
    - ./scripts/check_format.sh

build:
  stage: build
  script:
    - ./scripts/build_prod.sh
    - ./scripts/create_source_archive.sh
  artifacts:
    name: "RamBam"
    expire_in: 4 weeks
    paths:
      - build_prod/RamBam-*.deb
      - build_prod/RamBam-*.rpm
      - build_prod/RamBam-*.tar.gz
      - build_prod/RamBam-Source-*.tar.gz

upload_and_release:
  stage: release
  variables:
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/rambam/${CI_COMMIT_TAG}"
    RELEASE_LINKS_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/${CI_COMMIT_TAG}/assets/links"
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "melroy"
  script:
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build_prod/RamBam-v${CI_COMMIT_TAG}.deb
      ${PACKAGE_REGISTRY_URL}/RamBam-v${CI_COMMIT_TAG}.deb'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build_prod/RamBam-v${CI_COMMIT_TAG}.rpm
      ${PACKAGE_REGISTRY_URL}/RamBam-v${CI_COMMIT_TAG}.rpm'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build_prod/RamBam-v${CI_COMMIT_TAG}.tar.gz
      ${PACKAGE_REGISTRY_URL}/RamBam-v${CI_COMMIT_TAG}.tar.gz'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build_prod/RamBam-Source-v${CI_COMMIT_TAG}.tar.gz
      ${PACKAGE_REGISTRY_URL}/RamBam-Source-v${CI_COMMIT_TAG}.tar.gz'
    - 'curl --header "PRIVATE-TOKEN: ${ACCESS_TOKEN}" --header "Content-Type: application/json"
      --request POST --data "{\"name\":\"RamBam (Compressed binary)\",\"url\":\"${PACKAGE_REGISTRY_URL}/RamBam-v${CI_COMMIT_TAG}.tar.gz\",\"link_type\":\"package\"}"
      ${RELEASE_LINKS_URL}'
    - 'curl --header "PRIVATE-TOKEN: ${ACCESS_TOKEN}" --header "Content-Type: application/json"
      --request POST --data "{\"name\":\"RamBam (Red-Hat/Fedora/openSUSE)\",\"url\":\"${PACKAGE_REGISTRY_URL}/RamBam-v${CI_COMMIT_TAG}.rpm\",\"link_type\":\"package\"}"
      ${RELEASE_LINKS_URL}'
    - 'curl --header "PRIVATE-TOKEN: ${ACCESS_TOKEN}" --header "Content-Type: application/json"
      --request POST --data "{\"name\":\"RamBam (Debian/Ubuntu/Linux Mint)\",\"url\":\"${PACKAGE_REGISTRY_URL}/RamBam-v${CI_COMMIT_TAG}.deb\",\"link_type\":\"package\"}"
      ${RELEASE_LINKS_URL}'
    - 'curl --header "PRIVATE-TOKEN: ${ACCESS_TOKEN}" --header "Content-Type: application/json"
      --request POST --data "{\"name\":\"RamBam Code Source Archive (tar.gz)\",\"url\":\"${PACKAGE_REGISTRY_URL}/RamBam-Source-v${CI_COMMIT_TAG}.tar.gz\",\"link_type\":\"package\"}"
      ${RELEASE_LINKS_URL}'
#unit_test:
#  stage: test
#  script: ./build_prod/bin/runTests
#  cache:
#      key: "$CI_PIPELINE_ID"
#      policy: pull
#      paths:
#        - build_prod/bin/
