image: danger89/cmake:5.0

stages:
  - test
  - build

static_code_analysis:
  stage: test
  script:
    - cppcheck --version
    - ./scripts/cpp_check.sh

code_style_guidelines:
  stage: test
  script:
    - clang-format --version
    - ./scripts/check_format.sh

build:
  stage: build
  script: ./scripts/build_prod.sh
  artifacts:
    name: "RamBam"
    expire_in: 1 month
    paths:
      - build_prod/rambam
#unit_test:
#  stage: test
#  script: ./build_prod/bin/runTests
#  cache:
#      key: "$CI_PIPELINE_ID"
#      policy: pull
#      paths:
#        - build_prod/bin/
